// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVgE6jDHdjbSQ0_Zw6BW4stDrLm6l2098',
    appId: '1:264752395297:web:dd9b7058c1896af0829f60',
    messagingSenderId: '264752395297',
    projectId: 'shoppe-ecommerce-flutter',
    authDomain: 'shoppe-ecommerce-flutter.firebaseapp.com',
    storageBucket: 'shoppe-ecommerce-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtwgkfW4fcOt4AMxYqeJ0zpl3hKSkidZM',
    appId: '1:264752395297:android:8828a377050e06cc829f60',
    messagingSenderId: '264752395297',
    projectId: 'shoppe-ecommerce-flutter',
    storageBucket: 'shoppe-ecommerce-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8Xfn0xXYxfMrU5sCobHvTTYLFI5tmYw',
    appId: '1:264752395297:ios:c000341b1743b78d829f60',
    messagingSenderId: '264752395297',
    projectId: 'shoppe-ecommerce-flutter',
    storageBucket: 'shoppe-ecommerce-flutter.firebasestorage.app',
    iosBundleId: 'com.abdulsamad010.shoppeEcommerceFlutter',
  );
}
